scope: "zomato.com"
verbose: True
flags: ["-na", "--disable-gpu", "--window-size=1200,800", "--auto-open-devtools-for-tabs","--disable-popup-blocking"]
modules:
  processors:
    - path: "./data/modules/angular/unhider/"
      options: {}
    - path: "./data/modules/generic/unhider/"
  inspectors:
    - path: "./data/modules/generic/apifinder/"
      options: {}