scope: ""
verbose: False
script:
  path: "./data/scripts/ng-helpers.js"
  source: "https://onefootball.com/"
flags: ["-na", "--disable-gpu", "--window-size=1200,800", "--auto-open-devtools-for-tabs","--disable-popup-blocking"]
xhrBreakPoints:
  - "/v1/logs"
  - "/v1/accounts"
  - "/v1/sessions"
  - "/v1/api_keys"
modules:
  processors:
    - path: "/data/modules/processors/angular/prodModeHijacker/"
      options: {}
  inspectors:
    - path: "/data/modules/inspectors/generic/apifinder/"
      options:
        FilePath: "./logs/apifinds.txt"
