scope: ""
verbose: False
flags: ["-na", "--disable-gpu", "--window-size=1200,800", "--auto-open-devtools-for-tabs","--disable-popup-blocking"]
modules:
  processors:
    - path: "/data/modules/processors/generic/findreplace/"
      options:
        NewBodyPath: "/Users/alexuseche/Projects/Angular/js-mod.js"
        URL: "http://18.219.15.163/dist/juice-shop.min.js"